development:
  adapter: sqlite3
  database: db/development.sqlite
  host: localhost
  pool: 5
  timeout: 5000

production:
  url: 'HEROKU_POSTGRESQL_PINK_URL'
  adapter: postgresql
  database: mydb
  host: localhost 
  pool: 5
  timeout: 5000